/* =========================================================
   QUIZ BANK (EXPANDED)
========================================================= */
const quizBank = {
  beginner: [
    { type:"mc", q:"I ___ a book every night.", a:"read", o:["read","reads","reading"] },
    { type:"mc", q:"She ___ happy today.", a:"is", o:["is","are","am"] },
    { type:"mc", q:"Plural of 'cat'?", a:"cats", o:["cat","cats","cates"] },
    { type:"mc", q:"We ___ friends.", a:"are", o:["is","are","am"] },
    { type:"mc", q:"He ___ a dog.", a:"has", o:["has","have","having"] },
    { type:"mc", q:"I go to school ___ Monday.", a:"on", o:["in","on","at"] },
    { type:"mc", q:"There ___ two apples.", a:"are", o:["is","are","am"] },
    { type:"mc", q:"___ is my brother. (near)", a:"This", o:["This","That","Those"] },
    { type:"mc", q:"I want ___ apple.", a:"an", o:["a","an","the"] },
    { type:"mc", q:"Choose the correct word: 'I ___ milk.'", a:"like", o:["like","likes","liking"] },
    { type:"mc", q:"Which is correct?", a:"I am", o:["I is","I are","I am"] },
    { type: "mc", q: "I ___ to school every day.", a: "go", o: ["go", "goes", "going"] },
    { type: "mc", q: "We ___ visit our grandparents next week.", a: "will", o: ["will", "do", "does"] },
    { type: "mc", q: "They ___ a cat.", a: "have", o: ["has", "have", "having"] },
    { type: "mc", q: 'Plural of "bus"?', a: "buses", o: ["bus", "buss", "buses"] },
    { type: "mc", q: "I ___ a sandwich every day.", a: "make", o: ["make", "made", "making"] },
    { type: "mc", q: "I ___ going to clean my room.", a: "am", o: ["is", "are", "am"] },
    { type: "mc", q: "___ is your favorite color?", a: "What", o: ["What", "Which", "Who"] },
    { type: "mc", q: "I saw ___ interesting movie yesterday.", a: "an", o: ["a", "an", "the"] },
    { type: "mc", q: "I ___ coffee in the morning.", a: "like", o: ["like", "likes", "liked"] },
    { type: "mc", q: "___ of the two options is better?", a: "Which", o: ["Which", "What", "Who"] },
    { type: "mc", q: "How ___ oranges do you want?", a: "many", o: ["many", "much", "little"] },
    { type: "mc", q: "There ___ two books on the table.", a: "are", o: ["is", "are", "am"] },
    { type: "mc", q: 'Past of "go"?', a: "went", o: ["goed", "gone", "went"] },
    { type: "mc", q: "___ she going to the store?", a: "Is", o: ["Are", "Is", "Do"] },
    { type: "mc", q: "She ___ her phone at home yesterday.", a: "left", o: ["left", "leaves", "has left"] },
    { type: "mc", q: "Which is incorrect?", a: "Does I...?", o: ["Does she...?", "Do we...?", "Does I...?"] }
  ],

  intermediate: [
    { type:"mc", q:"If it rains, we ___ inside.", a:"will stay", o:["stay","will stay","stayed"] },
    { type:"mc", q:"She ___ here since 2020.", a:"has lived", o:["lived","has lived","lives"] },
    { type:"fill", prompt:"By the time I arrived, they ___ (start).", a:"had started", hint:"Past perfect" },
    { type:"mc", q:"He spoke quietly so nobody ___ hear.", a:"could", o:["can","could","will"] },
    { type:"mc", q:"This is the ___ idea I've heard.", a:"best", o:["good","better","best"] },
    { type: "fill", q: "She ___ (not watch) TV yesterday.", a: "did not watch" },
    { type:"fill", prompt:"Yesterday, I ___ (go) to the park.", a:"went", hint:"Past tense of go" },
    { type:"fill", prompt:"We ___ (play) soccer now.", a:"are playing", hint:"Present continuous" },
    { type:"fill", prompt:"She ___ (eat) breakfast at 7.", a:"eats", hint:"Simple present (she)" },
    { type:"fill", prompt:"They ___ (be) at home yesterday.", a:"were", hint:"Past of 'are'" },
    { type: "fill", q: "___ wants to play football?", a: "Who" },
    { type: "fill", q: "We ___ (see) that movie last week.", a: "saw" },
    { type: "fill", q: "There is ___ (zero) milk in the fridge.", a: "no" },
    { type:"mc", q:"I ___ to the gym twice a week.", a:"go", o:["go","goes","going"] },
    { type:"mc", q:"They ___ dinner when I called.", a:"were eating", o:["eat","were eating","have eaten"] },
    { type:"mc", q:"You ___ smoke here.", a:"must not", o:["must not","should","can"] },
    { type:"fill", prompt:"I have ___ (finish) my homework already.", a:"finished", hint:"Past participle" },
    { type:"mc", q:"If I ___ time, I would help you.", a:"had", o:["have","had","will have"] },
    { type:"mc", q:"This report is ___ than the last one.", a:"better", o:["good","better","best"] },
    { type:"fill", prompt:"She said she ___ (be) tired.", a:"was", hint:"Reported speech" },
    { type:"mc", q:"We decided ___ early.", a:"to leave", o:["leave","to leave","leaving"] },
    { type:"mc", q:"The car ___ yesterday.", a:"was repaired", o:["repaired","was repaired","is repair"] },
    { type:"fill", prompt:"I will call you when I ___ (arrive).", a:"arrive", hint:"Present simple in time clause" },
    { type: "mc", q: "I ___ wear a uniform at school.", a: "must", o: ["must", "have to", "can"] },
    { type: "fill", q: "When I was a child, I ___ (play) outside every day.", a: "used to play" },
    { type: "mc", q: "We decided ___ early.", a: "to leave", o: ["leave", "to leave", "leaving"] },
    { type: "fill", q: "She said she ___ (be) tired.", a: "was" },
    { type: "mc", q: "They ___ already eaten dinner before I arrived.", a: "had", o: ["have", "had", "has"] },
    { type: "mc", q: "He hurt ___ while playing football.", a: "himself", o: ["himself", "hiself", "himselve"] },
    { type: "mc", q: "I enjoy ___ books in my free time.", a: "reading", o: ["read", "reading", "to read"] },
    { type: "mc", q: "I did it all by ___.", a: "myself", o: ["myself", "me", "my"] },
    { type: "fill", q: "I enjoy ___ (watch) movies at night.", a: "watching" },
    { type: "mc", q: "The window ___ by the wind last night.", a: "was broken", o: ["broke", "was broken", "is break"] },
    { type: "mc", q: "He said that he ___ swim very well.", a: "could", o: ["can", "could", "was"] },
    { type: "fill", q: "I ___ finish my homework before I can go out.", a: "must" },
    { type: "mc", q: "He ___ be at the office, but I’m not sure.", a: "might", o: ["might", "will", "did"] },
    { type: "mc", q: "This is the ___ movie I’ve ever seen.", a: "funniest", o: ["funny", "funnier", "funniest"] },
    { type: "mc", q: "He ___ his homework every evening before dinner.", a: "does", o: ["do", "does", "did"] },
    { type: "mc", q: "Do you know where she ___ (live)?", a: "lives", o: ["live", "lives", "lived"] },
    { type: "mc", q: "This time tomorrow, we ___ on the plane.", a: "will be", o: ["are", "were", "will be"] },
    { type: "fill", q: "I can’t believe he ___ (forget) my birthday!", a: "forgot" },
    { type: "mc", q: "We should ___ our homework before watching TV.", a: "finish", o: ["finish", "to finish", "finished"] },
    { type: "mc", q: "If she studies hard, she ___ pass the exam.", a: "will", o: ["will", "would", "can"] }
  ],

  advanced: [
    { type:"mc", q:"Despite ___ tired, he continued.", a:"being", o:["be","being","to be"] },
    { type:"mc", q:"Not only ___ he apologize, but he fixed it.", a:"did", o:["do","did","does"] },
    { type:"fill", prompt:"Had I known earlier, I ___ (tell) you.", a:"would have told", hint:"Third conditional" },
    { type:"mc", q:"The proposal was rejected, ___ its benefits.", a:"despite", o:["because","despite","unless"] },
    { type:"mc", q:"Rarely ___ we see such a result.", a:"do", o:["do","did","does"] },
    { type:"mc", q:"Hardly ___ the meeting started when the power went out.", a:"had", o:["has","had","have"] },
    { type:"mc", q:"No sooner ___ I sat down than the phone rang.", a:"had", o:["did","had","have"] },
    { type:"mc", q:"It is essential that he ___ on time.", a:"be", o:["is","be","was"] },
    { type:"fill", prompt:"If she ___ (study) harder, she would have passed.", a:"had studied", hint:"Third conditional" },
    { type:"mc", q:"He acted as though he ___ everything.", a:"knew", o:["knows","knew","known"] },
    { type:"mc", q:"The more you practice, the ___ you become.", a:"better", o:["good","better","best"] },
    { type:"mc", q:"The report, ___ I expected, was incomplete.", a:"as", o:["as","because","unless"] },
    { type:"fill", prompt:"Seldom ___ we ___ such honesty. (use: do / witness)", a:"do witness", hint:"Inversion" },
    { type:"mc", q:"He refused to resign, ___ the pressure.", a:"regardless of", o:["because of","regardless of","in case"] },
    { type:"fill", prompt:"She insisted on ___ (receive) a full explanation.", a:"receiving", hint:"Gerund after 'insisted on'" },
    { type: "mc", q: "There isn’t ___ milk in the fridge.", a: "any", o: ["some", "any", "many"] },
    { type: "mc", q: "He slept ___ the meeting.", a: "during", o: ["during", "for", "while"] },
    { type: "mc", q: "She’s the girl ___ brother is a doctor.", a: "whose", o: ["whose", "who’s", "whom"] },
    { type: "fill", q: "The letters ___ (send) already.", a: "have been sent" },
    { type: "mc", q: "I would rather ___ at home than go out tonight.", a: "stay", o: ["stay", "staying", "to stay"] },
    { type: "mc", q: "___ the end, everything worked out well.", a: "in", o: ["in", "on", "at"] },
    { type: "mc", q: "What is the reason ___ his absence?", a: "for", o: ["on", "for", "of"] },
    { type: "fill", q: "The cause ___ the accident is still unknown.", a: "of" },
    { type: "mc", q: "When I arrived, they ___ already left.", a: "had", o: ["have", "had", "were"] },
    { type: "mc", q: "The cake ___ by my mother.", a: "was made", o: ["were made", "was made", "is made"] },
    { type: "fill", q: "They ___ (must / forget) the meeting.", a: "must have forgotten" },
    { type: "mc", q: "The house ___ last year.", a: "was built", o: ["was built", "is built", "had built"] },
    { type: "mc", q: "I would rather ___ a book than watch TV.", a: "read", o: ["read", "reading", "to read"] },
    { type: "fill", q: "“I love traveling.” — “___ do I.”", a: "so" },
    { type: "mc", q: "She looked exhausted because she ___ on the proposal all night.", a: "had been working", o: ["has been working", "had been working", "have been working"] },
    { type: "mc", q: "She answered the question ___.", a: "correctly", o: ["correct", "correctly", "correctedly"] },
    { type: "fill", q: "He ___ (realize) his mistake only after the email was sent.", a: "had realized" },
    { type: "mc", q: "Although he was tired, he finished his work ___ it was important.", a: "because", o: ["because", "but", "so"] },
    { type: "mc", q: "You ___ have locked the door.", a: "must", o: ["must", "were", "don't"] },
    { type: "fill", q: "I look forward to ___ (see) you.", a: "seeing" }
  ]
};

function pickQuestion(diff){
  const pool = quizBank[diff] || quizBank.beginner;
  return pool[Math.floor(Math.random()*pool.length)];
}

